[package]
name = "freminal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.29.1"
# tar = "0.4.42"
portable-pty = "0.8.1"
thiserror = "1.0.64"
conv = "0.3.3"
anyhow = "1.0.89"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
easy-cast = "0.5.2"
crossbeam-channel = "0.5.13"
path-clean = "1.0.1"

[build-dependencies]
tar = "0.4.42"
