[workspace]
members = ["freminal", "freminal-common", "terminal-emulator", "xtask"]
default-members = ["freminal", "freminal-common", "terminal-emulator"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Fred Clausen"]
license = "MIT"
description = "A terminal emulator written in Rust"
repository = "https://github.com/fredclausen/freminal"
documentation = "https://github.com/fred/freminal/README.md"
homepage = "https://github.com/fredclausen/freminal"
readme = "README.md"
rust-version = "1.82.0"
version = "0.1.0"

[workspace.dependencies]
eframe = { version = "0.29.1", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
    "wayland",
    "x11",
] }
egui = { version = "0.29.1", default-features = false, features = [
    "default_fonts",
    "persistence",
    "log",
] }
portable-pty = "0.8.1"
thiserror = "2.0.3"
conv = "0.3.3"
anyhow = "1.0.93"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
crossbeam-channel = "0.5.13"
unicode-segmentation = "1.12.0"
