[package]
name = "freminal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.28.1"
tar = "0.4.41"
nix = { version = "0.29.0", default-features = false, features = [
    "term",
    "process",
    "fs",
    "ioctl",
] }
tempfile = "3.12.0"
thiserror = "1.0.63"
tinyjson = "2.5.1"
conv = "0.3.3"
hex-string = "0.1.0"

[build-dependencies]
tar = "0.4.41"
