[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = ["xtask"]

[tasks.format]
condition = { profiles = ["development"] }
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.br]
workspace = false
command = "cargo"
args = ["build", "--release"]

[tasks.rr]
workspace = false
command = "cargo"
args = ["run", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.bench]
command = "cargo"
args = ["bench"]
dependencies = ["build"]

[tasks.x]
command = "cargo"
args = ["xtask", "ci"]
dependencies = [
  "install_typos",
  "install_markdown",
  "install_deny",
  "install_machete",
  "build",
]
workspace = false

[tasks.install_machete]
install_crate = { crate_name = "cargo-machete" }

[tasks.install_deny]
install_script = '''
# if deny is executable, we're good
if cargo deny --help &> /dev/null
then
    echo "deny is already installed"
else
    if command -v brew &> /dev/null
    then
        echo "Installing deny via brew"
        brew install cargo-deny
    elif command -v cargo &> /dev/null
    then
        echo "Installing deny via cargo"
        cargo install cargo-deny
    else
        echo "No package manager found to install deny"
        exit 1
    fi
fi
'''

[tasks.install_typos]
install_script = '''
# if typos is executable, we're good

if ! command -v typos &> /dev/null
then
    # if we have brew, install via brew
    if command -v brew &> /dev/null
    then
        echo "Installing typos via brew"
        brew install typos-cli
    elif command -v cargo &> /dev/null
    then
        echo "Installing typos via npm"
        cargo install typos-cli
    else
        echo "No package manager found to install typos"
        exit 1
    fi
else
    echo "typos is already installed"
fi
'''

[tasks.install_markdown]
install_script = '''
# if markdownlint-cli2 is executable, we're good

if ! command -v markdownlint-cli2 &> /dev/null
then
    # if we have brew, install via brew
    if command -v brew &> /dev/null
    then
        echo "Installing markdownlint-cli2 via brew"
        brew install markdownlint-cli2
    elif command -v npm &> /dev/null
    then
        echo "Installing markdownlint-cli2 via npm"
        npm install -g markdownlint-cli2
    else
        echo "No package manager found to install markdownlint-cli2"
        exit 1
    fi
else
    echo "markdownlint-cli2 is already installed"
fi
'''
