[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = ["xtask"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.bench]
command = "cargo"
args = ["bench"]
dependencies = ["build"]

# TODO: Define install deps for all the things xtask needs
[tasks.x]
command = "cargo"
args = ["xtask", "ci"]
dependencies = ["build"]
# workspace = false
