name: Deploy

on:
  # Enable manual running of action if necessary
  workflow_dispatch:

jobs:
  lint-formatting:
    name: Bundle Linux AMD64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo install bundle
          cargo bundle
