name: Deploy

on:
  # Enable manual running of action if necessary
  workflow_dispatch:

jobs:
  lint-formatting:
    name: Bundle Linux AMD64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Bundle
        uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo install cargo-bundle
          cargo bundle --release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: |
            target/release/bundle/deb/*.deb
