on:
  pull_request:
  push:
    branches:
      - main

name: Test with Code Coverage

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools
      - name: cargo install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov@v2.44.68
      - name: cargo llvm-cov
        run: cargo llvm-cov --all-features --lcov --output-path lcov.info
        env:
          CARGO_HUSKY_DONT_INSTALL_HOOKS: true
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v4.6.0
        with:
          # required for private repositories:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          fail_ci_if_error: true
